/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adarkroom;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.Media;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.Timer;
import java.io.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import sun.applet.Main;
import sun.audio.*;
import java.io.File;
import javax.sound.sampled.UnsupportedAudioFileException;

public class Window extends javax.swing.JFrame {
    
    // Variables required throughout the program.
    public int CountdownNum = 60;
    private javax.swing.Timer timer;
    public int FireTimes = 0;
    public static ArrayList<Wood> logs = new ArrayList<>();
    String[] WoodTypes = new String[]{"Cedar","Oak","Maple"};
    public int count = 0;
    public boolean FirstStage = false;
    public String Room;
    AudioClip click;
    
    public Window(){
        initComponents();
        
        URL urlClick = Window.class.getResource("log.wav");
        System.out.println(urlClick);
        click=Applet.newAudioClip(urlClick);
        
        //These Buttons are not required at the start so should not be visible.
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        //fullscreen:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        java.awt.event.ActionListener timerAction = new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e){
                doThing();
            }
        };
        
        //Game timer.
        timer = new javax.swing.Timer(1000, timerAction);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/fireplace-room-panelled-wood-49463380_1.jpg"))); // NOI18N
        jLabel1.setText("                   ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel2.setText("You are in a dark room.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        jLabel3.setText("There is an unlit fire in the centre of the room.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jButton1.setText("Add log to fire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 610, -1, -1));

        jLabel4.setText("Timer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, -1, -1));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, -1, -1));

        jButton3.setText("Approach Woman");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 569, -1, -1));

        jButton4.setText("Hello?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButton5.setText("Excuse me?");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton6.setText("Who are you?");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jButton7.setText("What are you doing?");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //At the start of the game the buttons function is to add logs to fire.
        if(jButton1.getText().contentEquals("Add log to fire")){
            //Calling the function that adds logs to the fire.
            LogToFire();
        }
        
        //Once logs have been added to fire the story should progress.
        //This should not run everytime however as the button will be reused, therefore it will
        //only run once when FirstStage boolean is not true yet.
        if(logs.isEmpty()&&FirstStage==false){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/fireplace-room-panelled-wood-49463380_6.jpg")));
            jButton1.setVisible(false);
            jLabel2.setText("Pheww you're safe - for now...");
            int delay = 2000;//specify the delay for the timer
            Timer timer2 = new Timer( delay, e -> {
              //The following code will be executed once the delay is reached
              jButton3.setVisible(true);
              jLabel2.setText("<html>AGHH! Now that it's brighter, you see a strange <br/>woman standing in the corner.</html>");
              jLabel3.setVisible(false);
            } );
            timer2.setRepeats( false );//make sure the timer only runs once
            timer2.start();
            FirstStage = true;
        }
        
        //Reusing the same button as a back button function.
        if(jButton1.getText().contentEquals("Back?")){
            GoBack(Room);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Button to approach the scary woman.
        Room = "ScaryWomanUpClose";
        jLabel2.setText("You decide to approach the woman.");
        jButton3.setVisible(false);
        jButton1.setText("Back?");
        jButton1.setVisible(true);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/ScaryWomanUpClose.jpg")));
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //jButtons 4-7 are all red hearings they will al kill you. So the following code removes
        //everything from the screen.
        jLabel2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/YouDied2.jpg")));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/YouDied2.jpg")));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/YouDied2.jpg")));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/YouDied2.jpg")));
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //Creating the window.
        Window myTimer = new Window();
        //Setting game timer to 0.
        myTimer.timer.restart();
       
        Random Rand = new Random();
        Scanner input = new Scanner(System.in);
        boolean next = true;

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                myTimer.setVisible(true);
            }
        });
    }
    
    public void doThing(){
        //Function to display my game timer.
        CountdownNum = CountdownNum - 1;
        String StringNum = Integer.toString(CountdownNum);
        jLabel4.setText(StringNum + " seconds.");
        if(CountdownNum > 0 && CountdownNum < 45){
            jLabel2.setText("You have 5 logs of varying size and type.");
            jLabel3.setVisible(false);
        }
        if(CountdownNum == 0){
            timer.stop();
            jButton1.setVisible(false);
            jLabel4.setText("You died, sorry");
        }
    }
    
    public static void ChopWood(ArrayList logs, String[] WoodTypes){
        //Function that gives the user random sizes and types of logs at the start of the game, using
        //The object Wood.java.
        Random Rand = new Random();
        for (int i = 0; i < 5; i++) {
            int Number = Rand.nextInt(2);
            int Size = Rand.nextInt(10);
            Wood log = new Wood(Size , WoodTypes[Number]);
            logs.add(log);
        }        
    }
    
    public void LogToFire(){
        //The following algorithm 'adds logs to the fire' and calculates how long the fire will last
        //based on the size and type of logs. It then adds this to the game timer.
        click.play();
        
        int FireTime = 0;
        
        jLabel2.setText("You have placed a log onto the fire.");
        jLabel3.setVisible(false);
        if(logs.isEmpty() && count != 5){
            ChopWood(logs, WoodTypes);
        }
        
        if(!logs.isEmpty()){
            if((logs.get(0).getWoodSize()) >= 3){
                FireTime = FireTime + 20; 
            }
            else if((logs.get(0).getWoodSize()) >= 6){
                FireTime = FireTime + 40;
            }
            else if((logs.get(0).getWoodSize()) >= 9){
                FireTime = FireTime + 90;
            }
            else{
                FireTime = FireTime + 10;
            }

            switch (logs.get(0).getWoodType()) {
                case "Cedar":
                    FireTime = FireTime + 0;
                    break;
                case "Maple":
                    FireTime = FireTime + 10;
                    break;
                default:
                    FireTime = FireTime + 20;
                    break;
            }
            if(FirstStage==false){
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/fireplace-room-panelled-wood-49463380_"+(count+2)+".jpg")));
            }
            logs.remove(0);
            count = count + 1;
        }
        else{
            jButton1.setVisible(false);
        }
        FireTimes = FireTimes + FireTime;
        jLabel3.setText("Fire will last for " + FireTimes + " seconds.");
        jLabel3.setVisible(true);
        CountdownNum = CountdownNum + FireTime;
    }
    
    public void GoBack(String Room){
        //Creating my back button function. Depending on the current room, The function will go back to
        //this.
        if(Room.equals("ScaryWomanUpClose")){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adarkroom/fireplace-room-panelled-wood-49463380_6.jpg")));
            jLabel2.setText("You leave approaching her for now.");
            jButton1.setVisible(false);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jButton6.setVisible(false);
            jButton7.setVisible(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
